# -*- coding: utf-8 -*-
"""
/***************************************************************************
 documentos
                                 A QGIS plugin
 plugin para apresentar timeline dos documentos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-22
        copyright            : (C) 2022 by Jhonatan
        email                : jhonatan.goncalves@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load documentos class from file documentos.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .documents import documentos
    return documentos(iface)
