# Form implementation generated from reading ui file 'd:\Projetos\plugin_QGIS\documents\documents_dialog_base.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1247, 600)
        Dialog.setMinimumSize(QtCore.QSize(1100, 0))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.tabWidget.setObjectName("tabWidget")
        self.documents = QtWidgets.QWidget()
        self.documents.setObjectName("documents")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.documents)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollAreaDocs = QtWidgets.QScrollArea(self.documents)
        self.scrollAreaDocs.setWidgetResizable(True)
        self.scrollAreaDocs.setObjectName("scrollAreaDocs")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 888, 525))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollAreaDocs.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollAreaDocs)
        self.tabWidget.addTab(self.documents, "")
        self.events = QtWidgets.QWidget()
        self.events.setObjectName("events")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.events)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollAreaEvents = QtWidgets.QScrollArea(self.events)
        self.scrollAreaEvents.setWidgetResizable(True)
        self.scrollAreaEvents.setObjectName("scrollAreaEvents")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 888, 525))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.scrollAreaEvents.setWidget(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_3.addWidget(self.scrollAreaEvents)
        self.tabWidget.addTab(self.events, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.listWidget, self.tabWidget)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Timeline"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents), _translate("Dialog", "Documentos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.events), _translate("Dialog", "Eventos"))
